config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  resources :conferences do
		collection do
			get :change_priority
		end
	end
	resources :proposals
	resources :session_configurations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conference.rb
class Conference < ApplicationRecord
	has_many :tracks
	has_many :proposals
	
	def generate_talks(priority_config)
		assigned_proposal_ids = Array.new
		track_seq 						= 0
		shortest_duration 		= self.proposals.order(duration_minute: 'asc').first.duration_minute
		longest_duration 			= self.proposals.order(duration_minute: 'desc').first.duration_minute

		# get total sessions duration (each track)
		available_duration = 0
		SessionConfiguration.order('start_time').all.each do |session_config|
			available_duration += (session_config.end_time - session_config.start_time) / 60 # in minutes
		end

		while (assigned_proposal_ids.length < self.proposals.length) do
			track_duration = available_duration

			# track loop
			while (track_duration > 0)
				if assigned_proposal_ids.length == self.proposals.length
					break
				end
				track_seq += 1
				track = Track.create(name: 'Track ' + track_seq.to_s, active: true, conference: self)

				# session loop
				SessionConfiguration.order('start_time').all.each do |session_config|
					session = Session.create(name: session_config.name, active: true, track: track)
					session_duration = (session_config.end_time - session_config.start_time) / 60 # in minutes

					# talk loop
					talks = Array.new
					prev_duration = 0
					prev_end_time = session_config.start_time

					# custom variable based on priority config
					if priority_config == '1'
						prev_duration = session_duration
						sorting = 'desc'
						comparison = '<'
						duration_reset_comparison = shortest_duration
						duration_reset = longest_duration
					else
						prev_duration = 0
						sorting = 'asc'
						comparison = '>'
						duration_reset_comparison = longest_duration
						duration_reset = shortest_duration
					end

					while (session_duration > 0)
						# make where script to exclude assigned proposal ids
						assigned_query = ''
						if assigned_proposal_ids.length != 0
							assigned_query = ' and id not in (' + assigned_proposal_ids.join(',') + ')'
						end

						# scenario 1: check if all proposal is assigned
						# if no proposals left exit loop
						if assigned_proposal_ids.length == self.proposals.length
							break
						# scenario 2: check if between range of longest and shortest
						# if between them, direct take
						elsif (session_duration >= shortest_duration && session_duration <= longest_duration)
							proposal = self.proposals
													.where('duration_minute ' + comparison + '= ?' + assigned_query, session_duration)
													.order(duration_minute: sorting)
													.first
						# scenario 3: check if prev_duration already hit limit
						# if yes, then reset to beginning
						elsif (prev_duration == duration_reset_comparison)
							proposal = self.proposals
													.where('duration_minute ' + comparison + '= ?' + assigned_query, duration_reset)
													.order(duration_minute: sorting)
													.first
						# scenario 4: get next record sequentially from prev duration
						# example desc: if prev duration = 60, aim 45 or 30
						else
							proposal = self.proposals
													.where('duration_minute ' + comparison + ' ?' + assigned_query, prev_duration)
													.order(duration_minute: sorting)
													.first
						end

						# check if scenarios above does not return a result
						# if nil then break
						break if proposal.nil?

						# start & end time calculation
						start_time = prev_end_time
						end_time = start_time + proposal.duration_minute.minute						
						talks << { name: proposal.name, duration_minute: proposal.duration_minute, start_time: start_time, end_time: end_time, active: true, session: session, proposal: proposal }

						prev_duration = proposal.duration_minute
						prev_end_time = end_time
						session_duration -= proposal.duration_minute
						track_duration -= proposal.duration_minute
						assigned_proposal_ids << proposal.id
					end

					# create talks
					Talk.create(talks)
				end # end session loop
			end # end track loop
		end # end proposal ids loop

		# update conference priority_configuration
		self.update_attributes(priority_configuration_id: priority_config)
	end
end

app/models/priority_configuration.rb
class PriorityConfiguration < ApplicationRecord
end

app/models/proposal.rb
class Proposal < ApplicationRecord
	belongs_to :conference
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :track
  has_many :talks
end

app/models/session_configuration.rb
class SessionConfiguration < ApplicationRecord
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :session
  belongs_to :proposal
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :conference
  has_many :sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
	before_action :edit, :only => [:update]

	def index
		@conferences = Conference.where(active: true)
	end

	def new
		@conference = Conference.new
	end

	def create
		conference = Conference.new(conference_params)
		conference.active = true
		if conference.save
			flash.notice = "New Conference has been created"
			redirect_to conferences_path
		else
			render 'new'
		end
	end

	def edit
		@conference = Conference.find(params[:id])
	end

	def update
		if @conference.update_attributes(conference_params)
			flash.notice = "Conference has been updated"
			redirect_to conferences_path
		else
			render 'edit'
		end
	end

	def destroy
		conference = Conference.find(params[:id])
		conference.update_attributes(:updated_at => Time.now)

		if conference.update_attributes(active: false)
			flash.notice = "Conference has been deleted"
		end
		redirect_to conferences_path
	end

	def change_priority
		conference = Conference.find(params[:id])

		# set to inactive
		conference.tracks.each do |track|
			track.update_attributes(active: false)
			track.sessions.each do |session|
				session.update_attributes(active: false)
				session.talks.update_all(active: false)
			end
		end

		# re-create record based on priority config
		conference.generate_talks(params[:config])
		redirect_to root_path
	end

	private
	def conference_params
		params.require(:conference).permit(:name)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@priority_configs = PriorityConfiguration.all
		@conferences = Conference.where(active: true)
	end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	before_action :edit, :only => [:update]
	before_action :load_data, :except => [:index]

	def load_data
		@conferences = Conference.all
	end

	def index
		@proposals = Proposal.all
	end

	def new
		@proposal = Proposal.new
	end

	def create
		proposal = Proposal.new(proposal_params)
		if proposal.save
			flash.notice = "New Proposal has been created"
			redirect_to proposals_path
		else
			render 'new'
		end
	end

	def edit
		@proposal = Proposal.find(params[:id])
	end

	def update
		if @proposal.update_attributes(proposal_params)
			flash.notice = "Proposal has been updated"
			redirect_to proposals_path
		else
			render 'edit'
		end
	end

	def destroy
		proposal = Proposal.find(params[:id])
		proposal.destroy
		redirect_to proposals_path
	end

	private
	def proposal_params
		params.require(:proposal).permit(:name, :duration_minute, :conference_id)
	end
end

app/controllers/session_configurations_controller.rb
class SessionConfigurationsController < ApplicationController
	before_action :edit, :only => [:update]

	def index
		@configs = SessionConfiguration.all
	end

	def edit
		@config = SessionConfiguration.find(params[:id])
		# @config.update_attributes(start_time: '10')
		# p asdf
	end

	def update
		if @config.update_attributes(config_params)
			flash.notice = "Configuration has been updated"
			redirect_to session_configurations_path
		else
			render 'edit'
		end
	end

	private
	def config_params
		params.require(:session_configuration).permit(:name, :start_time, :end_time)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/session_configurations_helper.rb
module SessionConfigurationsHelper
end

app/views/conferences/edit.html.erb
<div class="row gap-20 masonry pos-r">
  <div class="masonry-sizer col-md-6"></div>
  <div class="masonry-item col-md-6">
    <div class="bgc-white p-20 bd">
      <h6 class="c-grey-900">Edit Conference</h6>
      <div class="mT-30">
        <%= form_for @conference do |f| %>
          <div class="form-group">
            <%= f.label :name, t("title") %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/conferences/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Conferences</h4>
        <div class="text-right mb-3">
          <%= link_to new_conference_path, class: "btn btn-primary" do %>
            <i class="ti-plus"></i> Add New Conference
          <% end %>
        </div>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Created at</th>
              <th>Updated at</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          	<% @conferences.each do |conference| %>
          		<tr>
          			<td><%= conference.name %></td>
          			<td><%= conference.created_at.strftime("%d %b %Y") if conference.created_at %></td>
          			<td><%= conference.updated_at.strftime("%d %b %Y") if conference.updated_at %></td>
                <td>
                  <%= link_to root_path, alt: "Show details" do %>
                    <i class="c-blue-500 ti-info-alt"></i>
                  <% end %>
                  &nbsp;
                  <%= link_to edit_conference_path(conference.id), alt: "Edit" do %>
                    <i class="c-orange-500 ti-pencil-alt"></i>
                  <% end %>
                  &nbsp;
                  <%= link_to conference_path(conference.id), alt: "Delete",  method: :delete, data: { confirm: 'Are you sure want to do this ?' }  do %>
                    <i class="c-red-500 ti-trash"></i>
                  <% end %>
                </td>
          		</tr>
          	<% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/conferences/new.html.erb
<div class="row gap-20 masonry pos-r">
  <div class="masonry-sizer col-md-6"></div>
  <div class="masonry-item col-md-6">
    <div class="bgc-white p-20 bd">
      <h6 class="c-grey-900">New Conference</h6>
      <div class="mT-30">
        <%= form_for @conference do |f| %>
          <div class="form-group">
            <%= f.label :name, t("title") %>
            <%= f.text_field :name, :class => "form-control" %>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<% @conferences.each do |conference| %>
<%= hidden_field_tag "conference_id", conference.id %>
<div class="row">
	<div class="col-md-12">
		<div class="bgc-white p-20 bd">
			<div class="d-flex">
				<div class="mr-auto">
		      <h3 class="c-grey-900"><%= conference.name %></h3>
				</div>
				<div class="ml-auto">
					<%= select_tag "priority_configuration", options_from_collection_for_select(@priority_configs, "id", "name", conference.priority_configuration_id), class: "form-control d-inline-block", style: "width:73%;" %>
					<button type="button" class="btn btn-primary" id="btn-priority-config">
						<i class="ti-reload"></i> Change
					</button>
				</div>
			</div>
      <div class="mT-30">
				<% conference.tracks.where(active: true).each do |track| %>
					<h5 class="c-grey-900 mt-4"><%= track.name %></h5>
					<% last_talk_end_time = nil %>
					<% track.sessions.where(active: true).each do |session| %>
						<h6 class="c-grey-900"><%= session.name %></h6>
						<div class="pl-5">
							<% session.talks.where(active: true).each do |talk| %>
								<div class="row">
									<div class="col-md-2"><%= talk.start_time.strftime("%H:%M") if talk.start_time %> - <%= talk.end_time.strftime("%H:%M") if talk.end_time %></div>
									<div class="col-md-5"><%= talk.name %></div>
									<div class="col-md-2 mr-auto"><%= talk.duration_minute %> minutes</div>
								</div>
								<% last_talk_end_time = talk.end_time %>
								<!-- lunch -->
								<% if (talk.end_time) && (talk.end_time.strftime("%H:%M") == '12:00') %>
									<div class="row">
										<div class="col-md-2">12:00 - 13:00</div>
										<div class="col-md-5">Lunch</div>
										<div class="col-md-2 mr-auto">60 minutes</div>
									</div>
								<% end %>
							<% end %>
						</div>
					<% end %>
					<!-- networking -->
					<div class="pl-5">
						<div class="row">
							<div class="col-md-2"><%= last_talk_end_time.strftime("%H:%M") if last_talk_end_time %></div>
							<div class="col-md-5 mr-auto">Networking Event</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/proposals/edit.html.erb
<div class="row gap-20 masonry pos-r">
  <div class="masonry-sizer col-md-6"></div>
  <div class="masonry-item col-md-6">
    <div class="bgc-white p-20 bd">
      <h6 class="c-grey-900">Edit Proposal</h6>
      <div class="mT-30">
        <%= form_for @proposal do |f| %>
          <div class="form-group">
            <%= f.label :name, t("title") %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :duration_minute, t("Duration (minutes)") %>
            <%= f.number_field :duration_minute, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :conference_id, t("conference") %>
            <%= f.select :conference_id, options_from_collection_for_select(@conferences, "id", "name", @proposal.conference_id), {}, {class: "form-control"} %>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/proposals/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Proposals</h4>
        <div class="text-right mb-3">
          <%= link_to new_proposal_path, class: "btn btn-primary" do %>
            <i class="ti-plus"></i> Add New Proposal
          <% end %>
        </div>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Duration (minutes)</th>
              <th>Conference</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          	<% @proposals.each do |proposal| %>
          		<tr>
          			<td><%= proposal.name %></td>
          			<td><%= proposal.duration_minute %></td>
          			<td><%= proposal.conference.name %></td>
                <td>
                  <%= link_to edit_proposal_path(proposal.id), alt: "Edit" do %>
                    <i class="c-orange-500 ti-pencil-alt"></i>
                  <% end %>
                  &nbsp;
                  <%= link_to proposal_path(proposal.id), alt: "Delete",  method: :delete, data: { confirm: 'Are you sure want to do this ?' }  do %>
                    <i class="c-red-500 ti-trash"></i>
                  <% end %>
                </td>
          		</tr>
          	<% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/proposals/new.html.erb
<div class="row gap-20 masonry pos-r">
  <div class="masonry-sizer col-md-6"></div>
  <div class="masonry-item col-md-6">
    <div class="bgc-white p-20 bd">
      <h6 class="c-grey-900">New Proposal</h6>
      <div class="mT-30">
        <%= form_for @proposal do |f| %>
          <div class="form-group">
            <%= f.label :name, t("title") %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :duration_minute, t("Duration (minutes)") %>
            <%= f.number_field :duration_minute, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :conference_id, t("conference") %>
            <%= f.select :conference_id, options_from_collection_for_select(@conferences, "id", "name"), {}, {class: "form-control"} %>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/session_configurations/edit.html.erb
<div class="row gap-20 masonry pos-r">
  <div class="masonry-sizer col-md-6"></div>
  <div class="masonry-item col-md-6">
    <div class="bgc-white p-20 bd">
      <h6 class="c-grey-900">Edit Session Configuration</h6>
      <div class="mT-30">
        <%= form_for @config do |f| %>
          <div class="form-group">
            <%= f.label :name, t("name") %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :start_time, t("start_time") %>
            <%= f.hidden_field :start_time, value: (f.object.start_time.strftime("%H:%M") if f.object.start_time) %>
            <div class="row">
              <div class="col-md-6">
                <select id="start_time_hour" class="form-control session_configuration_select_time">
                  <option value="00">00</option>
                  <option value="01">01</option>
                  <option value="02">02</option>
                  <option value="03">03</option>
                  <option value="04">04</option>
                  <option value="05">05</option>
                  <option value="06">06</option>
                  <option value="07">07</option>
                  <option value="08">08</option>
                  <option value="09">09</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  <option value="13">13</option>
                  <option value="14">14</option>
                  <option value="15">15</option>
                  <option value="16">16</option>
                  <option value="17">17</option>
                  <option value="18">18</option>
                  <option value="19">19</option>
                  <option value="20">20</option>
                  <option value="21">21</option>
                  <option value="22">22</option>
                  <option value="23">23</option>
                </select>
              </div>
              <div class="col-md-6">
                <select id="start_time_minute" class="form-control session_configuration_select_time">
                  <option value="00">00</option>
                  <option value="01">01</option>
                  <option value="02">02</option>
                  <option value="03">03</option>
                  <option value="04">04</option>
                  <option value="05">05</option>
                  <option value="06">06</option>
                  <option value="07">07</option>
                  <option value="08">08</option>
                  <option value="09">09</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  <option value="13">13</option>
                  <option value="14">14</option>
                  <option value="15">15</option>
                  <option value="16">16</option>
                  <option value="17">17</option>
                  <option value="18">18</option>
                  <option value="19">19</option>
                  <option value="20">20</option>
                  <option value="21">21</option>
                  <option value="22">22</option>
                  <option value="23">23</option>
                  <option value="24">24</option>
                  <option value="25">25</option>
                  <option value="26">26</option>
                  <option value="27">27</option>
                  <option value="28">28</option>
                  <option value="29">29</option>
                  <option value="30">30</option>
                  <option value="31">31</option>
                  <option value="32">32</option>
                  <option value="33">33</option>
                  <option value="34">34</option>
                  <option value="35">35</option>
                  <option value="36">36</option>
                  <option value="37">37</option>
                  <option value="38">38</option>
                  <option value="39">39</option>
                  <option value="40">40</option>
                  <option value="41">41</option>
                  <option value="42">42</option>
                  <option value="43">43</option>
                  <option value="44">44</option>
                  <option value="45">45</option>
                  <option value="46">46</option>
                  <option value="47">47</option>
                  <option value="48">48</option>
                  <option value="49">49</option>
                  <option value="50">50</option>
                  <option value="51">51</option>
                  <option value="52">52</option>
                  <option value="53">53</option>
                  <option value="54">54</option>
                  <option value="55">55</option>
                  <option value="56">56</option>
                  <option value="57">57</option>
                  <option value="58">58</option>
                  <option value="59">59</option>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :end_time, t("end_time") %>
            <%= f.hidden_field :end_time, value: (f.object.end_time.strftime("%H:%M") if f.object.end_time) %>
            <div class="row">
              <div class="col-md-6">
                <select id="end_time_hour" class="form-control session_configuration_select_time">
                  <option value="00">00</option>
                  <option value="01">01</option>
                  <option value="02">02</option>
                  <option value="03">03</option>
                  <option value="04">04</option>
                  <option value="05">05</option>
                  <option value="06">06</option>
                  <option value="07">07</option>
                  <option value="08">08</option>
                  <option value="09">09</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  <option value="13">13</option>
                  <option value="14">14</option>
                  <option value="15">15</option>
                  <option value="16">16</option>
                  <option value="17">17</option>
                  <option value="18">18</option>
                  <option value="19">19</option>
                  <option value="20">20</option>
                  <option value="21">21</option>
                  <option value="22">22</option>
                  <option value="23">23</option>
                </select>
              </div>
              <div class="col-md-6">
                <select id="end_time_minute" class="form-control session_configuration_select_time">
                  <option value="00">00</option>
                  <option value="01">01</option>
                  <option value="02">02</option>
                  <option value="03">03</option>
                  <option value="04">04</option>
                  <option value="05">05</option>
                  <option value="06">06</option>
                  <option value="07">07</option>
                  <option value="08">08</option>
                  <option value="09">09</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  <option value="13">13</option>
                  <option value="14">14</option>
                  <option value="15">15</option>
                  <option value="16">16</option>
                  <option value="17">17</option>
                  <option value="18">18</option>
                  <option value="19">19</option>
                  <option value="20">20</option>
                  <option value="21">21</option>
                  <option value="22">22</option>
                  <option value="23">23</option>
                  <option value="24">24</option>
                  <option value="25">25</option>
                  <option value="26">26</option>
                  <option value="27">27</option>
                  <option value="28">28</option>
                  <option value="29">29</option>
                  <option value="30">30</option>
                  <option value="31">31</option>
                  <option value="32">32</option>
                  <option value="33">33</option>
                  <option value="34">34</option>
                  <option value="35">35</option>
                  <option value="36">36</option>
                  <option value="37">37</option>
                  <option value="38">38</option>
                  <option value="39">39</option>
                  <option value="40">40</option>
                  <option value="41">41</option>
                  <option value="42">42</option>
                  <option value="43">43</option>
                  <option value="44">44</option>
                  <option value="45">45</option>
                  <option value="46">46</option>
                  <option value="47">47</option>
                  <option value="48">48</option>
                  <option value="49">49</option>
                  <option value="50">50</option>
                  <option value="51">51</option>
                  <option value="52">52</option>
                  <option value="53">53</option>
                  <option value="54">54</option>
                  <option value="55">55</option>
                  <option value="56">56</option>
                  <option value="57">57</option>
                  <option value="58">58</option>
                  <option value="59">59</option>
                </select>
              </div>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/session_configurations/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Session Configurations</h4>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Start Time</th>
              <th>End Time</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @configs.each do |config| %>
              <tr>
                <td><%= config.name %></td>
                <td><%= config.start_time.strftime("%H:%M") if config.start_time %></td>
                <td><%= config.end_time.strftime("%H:%M") if config.end_time %></td>
                <td>
                  <%= link_to edit_session_configuration_path(config.id), alt: "Edit" do %>
                    <i class="c-orange-500 ti-pencil-alt"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>